#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Commands\ServeCommand;

$application = new Application();

$application->add(new ServeCommand());

try {
    $application->run();
} catch (Exception $e) {
    echo $e->getMessage();
}